[versions]
agp = "9.4.0"
hotwire-native = "1.3.1"

[libraries]
hotwire-core = { group = "dev.hotwire", name = "core", version.ref = "hotwire-native" }
hotwire-navigation-fragments = { group = "dev.hotwire", name = "navigation-fragments", version.ref = "hotwire-native" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
